const designTokens = {
    colors: {
        "primary-container": "#1a73e8",
        "primary": "#005bbf",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004f58",
        "tertiary-fixed": "#94f990",
        "surface-container": "#edeeef",
        "on-primary-fixed": "#001a41",
        "inverse-surface": "#2e3132",
        "background": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "secondary": "#006874",
        "tertiary": "#006b1b",
        "on-primary-container": "#ffffff",
        "surface": "#f8f9fa",
        "outline": "#727785",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002204",
        "on-secondary-container": "#006b77",
        "on-background": "#191c1d",
        "on-surface-variant": "#414754",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005313",
        "tertiary-container": "#1e862d",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#adc7ff",
        "tertiary-fixed-dim": "#78dc77",
        "inverse-primary": "#adc7ff",
        "secondary-fixed": "#97f0ff",
        "on-primary": "#ffffff",
        "surface-tint": "#005bc0",
        "surface-variant": "#e1e3e4",
        "secondary-fixed-dim": "#66d6e7",
        "secondary-container": "#7fedfe",
        "on-secondary-fixed": "#001f24",
        "outline-variant": "#c1c6d6",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004493",
        "on-tertiary-container": "#f7fff1",
        "surface-container-lowest": "#ffffff"
    },
    borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
    },
    spacing: {
        "inline-gap": "0.5rem",
        "container-padding": "1rem",
        "section-margin": "1.5rem",
        "stack-gap": "0.75rem"
    },
    fontFamily: {
        "label-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-sm": ["Manrope"],
        "headline-md-mobile": ["Manrope"],
        "body-md": ["Manrope"],
        "label-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "display": ["Manrope"]
    },
    fontSize: {
        "label-md": [12, { lineHeight: 16, letterSpacing: 0.5, fontWeight: "600" }],
        "body-lg": [16, { lineHeight: 24, fontWeight: "500" }],
        "headline-sm": [18, { lineHeight: 24, fontWeight: "600" }],
        "headline-md-mobile": [18, { lineHeight: 24, fontWeight: "700" }],
        "body-md": [14, { lineHeight: 20, fontWeight: "400" }],
        "label-sm": [10, { lineHeight: 14, fontWeight: "500" }],
        "headline-md": [20, { lineHeight: 28, fontWeight: "700" }],
        "display": [24, { lineHeight: 32, fontWeight: "700" }]
    }
};

export default designTokens;